healthCheckTimeout: 1800
logLevel: info
metricsMaxInMemory: 1000
sendLoadingState: true
includeAliasesInList: true

models:
  "qwen3.5-0.8b":
    proxy: "http://127.0.0.1:9999"
    cmd: >
      /app/llama-server
      --model /models/Qwen3.5-0.8B.Q4_K_M-00001-of-00001.gguf
      --alias qwen3.5-0.8b
      --port 9999
      --parallel 4
      --webui llamacpp
      --jinja
      --ctx-size 32768
      -fa on
      --temp 1.0 --top-p 1.0 --top-k 20 --min-p 0 --presence-penalty 2.0 --repeat-penalty 1.0
    aliases:
      - "qwen3.5-0.8b"
      - "Qwen3.5-0.8B"
      - "Qwen/Qwen3.5-0.8B"
    filters:
      setParamsByID:
        "${MODEL_ID}:vl":
          temperature: 0.7
          top_p: 0.8
          presence_penalty: 1.5
        "${MODEL_ID}:thinking":
          temperature: 1.0
          top_p: 0.95
          presence_penalty: 1.5
          chat_template_kwargs:
            enable_thinking: true